In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

In [2]:
labels = pd.read_csv('labels.csv')

In [3]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

In [4]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [5]:
radiologist_accuracy

0.8993288590604027

In [6]:
confusion_matrix(labels.perfect_labeler.values, labels.radiologist.values, labels=['cancer','benign'])

array([[ 25,   4],
       [ 11, 109]], dtype=int64)

In [7]:
labels = labels.replace('cancer', 1).replace('benign', 0)
labels.head()

perfect_labeler  radiologist  algorithm
0                1            1       0.99
1                1            1       0.94
2                1            1       0.73
3                1            1       0.82
4                1            1       0.98

In [8]:
algorithm_thresh = (labels.algorithm > 0.5)

In [9]:
confusion_matrix(labels.perfect_labeler.values, algorithm_thresh, labels=[1,0])

array([[ 21,   8],
       [  8, 112]], dtype=int64)

In [10]:
algorithm_thresh = (labels.algorithm > 0.4)

In [11]:
confusion_matrix(labels.perfect_labeler.values, algorithm_thresh, labels=[1,0])

array([[ 25,   4],
       [ 16, 104]], dtype=int64)

In [12]:
algorithm_thresh = (labels.algorithm > 0.6)

In [13]:
confusion_matrix(labels.perfect_labeler.values, algorithm_thresh, labels=[1,0])

array([[ 20,   9],
       [  5, 115]], dtype=int64)

In [14]:
algorithm_thresh = (labels.algorithm > 0.5)

In [15]:
confusion_matrix(labels.radiologist.values, algorithm_thresh, labels=[1,0])

array([[ 23,  13],
       [  6, 107]], dtype=int64)